### ISSUE TITLE
Show/hide keyboard

### ISSUE THREAD

**Issue by mdznr** [peterhajas/Genesis#4]
You must tap first line to bring up keyboard (maybe automatically bring it up) when there is a new file
Also, you are unable to hide keyboard when scrolling (similar to that of Messages)

**Comment by peterhajas** [comment]
Genesis now hides the keyboard on scroll as of c4876298491d15b7dc739895b1577c7bc7faab54.

Working on the other issue you mentioned.

**Comment by peterhajas** [comment]
Genesis can now hide the keyboard using a button above the keyboard.
