### ISSUE TITLE
"Message was not in compressed format." on message receipt

### ISSUE THREAD

**Issue by peterhajas** [peterhajas/Genesis#7]
If I force the client to accept any version number (to temporarily fix #6), the client cannot interpret messages from the server as they are not in compressed format.

These issues may relate to the recent switch from `JSONKit` to `NSJsonSerialization`.

**Comment by jeffh** [comment]
network manager needs to do login after connecting (via the callback). Otherwise it is async behavior where login could be sent before verifying the protocol version (connection handshake). 
- Jeff

**Comment by peterhajas** [comment]
Thanks Jeff!

Is this the issue I was experiencing? If I log in in an asynchronous behavior, is the API functional?

**Comment by peterhajas** [comment]
This has been fixed with asynchronous login.
